site_name: Sofom Cloud - Documentación


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  language: es

  palette:
    # ─────────────────────────────
    # Modo claro (default)
    # ─────────────────────────────
    - scheme: default
      primary: blue grey

nav:
  - Inicio: index.md
  - Estructura de documentos: estructura_documentos.md
  - Guía de contribución: guia_contribucion.md
  - Sistema:
    - Simulador:
      - Simulador: sistema/simulador/simulador.md
    - Créditos:
      - Créditos: sistema/creditos/creditos.md
    - Dashboard:
      - Dashboard: sistema/dashboard/dashboard.md
      - Reportes: sistema/dashboard/reportes.md
    - Clientes:
      - Clientes: sistema/clientes/clientes.md
    - Bancos:
      - Bancos: sistema/bancos/bancos.md
    - Tesorería:
      - Tesorería: sistema/tesoreria/tesoreria.md
    - Call Center:
      - Call Center: sistema/callcenter/callcenter.md
    - Reportes:
      - Reportes: sistema/reportes/reportes.md
    - SIC:
      - SIC: sistema/sic/sic.md
    - Conducef:
      - Conducef: sistema/conducef/conducef.md
    - Administración de Riesgos:
      - Administración de Riesgos: sistema/riesgos/riesgos.md
    - Dirección:
      - Dirección: sistema/direccion/direccion.md
      - Productos: sistema/direccion/productos.md
    - Seguridad:
      - Seguridad: sistema/seguridad/seguridad.md
    - Reporteador:
      - Reporteador: sistema/reporteador/reporteador.md
    - Soporte:
      - Soporte: sistema/soporte/soporte.md
  - Desarrollo:
    - Base de datos:
      - CREDITOS: 
        - TABLAS: 
          - Credito: desarrollo/base_datos/CREDITOS/tablas/Credito.md
      - GENERAL:
        - TABLAS: 
          - Producto: desarrollo/base_datos/GENERAL/tablas/Producto.md
          - ProductoDetalle: desarrollo/base_datos/GENERAL/tablas/ProductoDetalle.md
          - ProductoCatalogo: desarrollo/base_datos/GENERAL/tablas/ProductoCatalogo.md
          - ProductoDetalleCatalogo: desarrollo/base_datos/GENERAL/tablas/ProductoDetalleCatalogo.md
          - ProductoDetalleCatalogoNaturaleza: desarrollo/base_datos/GENERAL/tablas/ProductoDetalleCatalogoNaturaleza.md
          - ProductoDocumento: desarrollo/base_datos/GENERAL/tablas/ProductoDocumento.md
          - ProductoImpacto: desarrollo/base_datos/GENERAL/tablas/ProductoImpacto.md
          - ProductoMetodosCalculo: desarrollo/base_datos/GENERAL/tablas/ProductoMetodosCalculo.md
          - ProductosImpacto: desarrollo/base_datos/GENERAL/tablas/ProductosImpacto.md
          - MetodoCalculo: desarrollo/base_datos/GENERAL/tablas/MetodoCalculo.md
          - SubmetodoCalculo: desarrollo/base_datos/GENERAL/tablas/SubmetodoCalculo.md
      
    - API:
      - Endpoints: 
        - Productos: desarrollo/api/endpoints/productos.md
        - Ciudades: desarrollo/api/endpoints/ciudades.md
        - Empresas: desarrollo/api/endpoints/empresas.md
        - Estado civil: desarrollo/api/endpoints/estado civil.md
        - Locaciones: desarrollo/api/endpoints/locaciones.md
        - Metodo calculo: desarrollo/api/endpoints/metodo calculo.md
        - Moneda: desarrollo/api/endpoints/moneda.md
        - Nacionalidades: desarrollo/api/endpoints/nacionalidades.md
        - Periodo pago: desarrollo/api/endpoints/periodopago.md
        - Regimen fiscal: desarrollo/api/endpoints/regimen fiscal.md
        - Reportes: desarrollo/api/endpoints/reportes.md
        - Riesgos: desarrollo/api/endpoints/riesgos.md
        - Submetodo calculo: desarrollo/api/endpoints/submetodo calculo.md
        - Tipos de gracia: desarrollo/api/endpoints/tipos gracia.md
      - Modelos: desarrollo/api/modelos
      - Autenticación: desarrollo/api/autenticacion
      - Configuración: desarrollo/api/configuracion
      - Funciones:  
        - Productos: desarrollo/api/funciones/productos.md
        - Ciudades: desarrollo/api/funciones/ciudades.md
        - Empresas: desarrollo/api/funciones/empresas.md
        - Estado civil: desarrollo/api/funciones/estado civil.md
        - Locaciones: desarrollo/api/funciones/locaciones.md
        - Metodo calculo: desarrollo/api/funciones/metodo calculo.md
        - Moneda: desarrollo/api/funciones/moneda.md
        - Nacionalidades: desarrollo/api/funciones/nacionalidades.md
        - Periodo pago: desarrollo/api/funciones/periodopago.md
        - Regimen fiscal: desarrollo/api/funciones/regimen fiscal.md
        - Reportes: desarrollo/api/funciones/reportes.md
        - Riesgos: desarrollo/api/funciones/riesgos.md
        - Submetodo calculo: desarrollo/api/funciones/submetodo calculo.md
        - Tipos de gracia: desarrollo/api/funciones/tipos gracia.md
    - SOFOM:
      - Backend:
        - Funciones:
          - Productos: desarrollo/sofom/backend/funciones/productos.md
          - Catalogos: desarrollo/sofom/backend/funciones/catalogos.md
          - Reportes: desarrollo/sofom/backend/funciones/reportes.md
          - Riesgos: desarrollo/sofom/backend/funciones/riesgos.md
      - Frontend: 
        - Funciones: 
          - Productos: desarrollo/sofom/frontend/funciones/productos.md
    - API ICE-CORE:
      - Endpoints: 
        - Productos: desarrollo/api_ice_core/endpoints/productos.md
        - Conceptos: desarrollo/api_ice_core/endpoints/conceptos.md
      - Modelos: desarrollo/api/modelos
      - Autenticación: desarrollo/api/autenticacion
      - Configuración: desarrollo/api/configuracion
      - Funciones:  
        - Productos: desarrollo/api_ice_core/funciones/productos.md
        - Conceptos: desarrollo/api_ice_core/funciones/conceptos.md
    - SOFOM ICE-CORE:
      - Backend:
        - Funciones:
          - Productos: desarrollo/sofom_ice_core/backend/funciones/productos.md
          - Conceptos: desarrollo/sofom_ice_core/backend/funciones/conceptos.md
      - Frontend: 
        - Funciones: 
          - Productos: desarrollo/sofom_ice_core/frontend/funciones/productos.md
          - Conceptos: desarrollo/sofom_ice_core/frontend/funciones/conceptos.md
extra_css:
  - styles/base.css

